### ISSUE TITLE
Wrong return type when register as luaOverloads

### ISSUE THREAD

**Issue by Domain** [BradleyChatha/lumars#19]
```
auto lua = new LuaState(null);
lua.register!(
    luaOverloads!(
        (int a) { return "123"; },
        (string a) { return "abc"; },
        (int a, string b) { return "!@#"; }
    )
)("overloaded");

lua.doString(`
    assert(overloaded(1) == "123")
    assert(overloaded("2") == "abc")
    assert(overloaded(1, "2") == "!@#")
`);
```
All of them return number 1.

**Comment by BradleyChatha** [comment]
That's... odd as well.

Is this happening using your replacment Lua library, or are you still using the bundled one here?

Really is a kick in the butt for me to add more platforms into the CI. I'll see if I can get some of your issues sorted today.

**Comment by Domain** [comment]
https://github.com/BradleyChatha/lumars/blob/1c3def35549cd6d0088b74f077ca5eeaeffa4cb1/source/lumars/function_.d#L531

https://github.com/BradleyChatha/lumars/blob/1c3def35549cd6d0088b74f077ca5eeaeffa4cb1/source/lumars/function_.d#L416

**Comment by Domain** [comment]
That is because luaOverloads return int

**Comment by BradleyChatha** [comment]
That's normal. Normally when Lua calls a foreign function you need to return an int to say how many return values you've actually returned.

`luaCWrapperSmart` is the layer that allows you to return like a normal D function, since it then figures out the correct `int` value to return to Lua. `luaOverloads` is just forwarding this value back.

The real reason is I'm a complete idiot and I didn't write a good enough unittest. `LuaState.register` unconditionally wraps the function you give it around `luaCWrapperSmart` because for some strange reason I thought that wouldn't happen.

... Though the fact `luaOverloads` returns `auto` means I may have *completely* misunderstood what I was doing, since that doesn't make much sense.

*sigh* I'll get that fixed up as well now, my apologies...
